// Generated by Apple Swift version 6.2.3 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef DYNAMICLINKS_SWIFT_H
#define DYNAMICLINKS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DynamicLinks",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
/// Deferred Deeplink 数据
/// 当用户通过 Deeplink 跳转到 App Store 下载 App，首次打开时可以获取原始链接数据
SWIFT_CLASS("_TtC12DynamicLinks20DeferredDeeplinkData")
@interface DeferredDeeplinkData
/// 是否找到延迟深链
@property (nonatomic, readonly) BOOL found;
/// 原始链接数据
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable linkData;
/// 获取原始 Deeplink ID
@property (nonatomic, readonly, copy) NSString * _Nullable deeplinkId;
/// 获取 Project ID
@property (nonatomic, readonly, copy) NSString * _Nullable projectId;
/// 获取原始 URL
@property (nonatomic, readonly, copy) NSString * _Nullable originalUrl;
/// 获取 UTM Source
@property (nonatomic, readonly, copy) NSString * _Nullable utmSource;
/// 获取 UTM Medium
@property (nonatomic, readonly, copy) NSString * _Nullable utmMedium;
/// 获取 UTM Campaign
@property (nonatomic, readonly, copy) NSString * _Nullable utmCampaign;
/// 获取 Referer
@property (nonatomic, readonly, copy) NSString * _Nullable referer;
/// 获取自定义数据
- (id _Nullable)getCustomDataWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
@end

@class NSURL;
/// 表示一个解析后的动态链接
/// 负责从长链接中提取深度链接、UTM 参数和最低 App 版本要求
SWIFT_CLASS("_TtC12DynamicLinks11DynamicLink")
@interface DynamicLink : NSObject
/// 提取的深度链接 URL
@property (nonatomic, readonly, copy) NSURL * _Nullable url;
/// 从长链接中提取的 UTM 参数，用于追踪目的
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull utmParameters;
/// 能够打开此链接的最低 App 版本 (从 “imv” 参数提取，iOS 特有)
@property (nonatomic, readonly, copy) NSString * _Nullable minimumAppVersion;
/// 从长链接初始化 DynamicLink
/// \param longLink 包含动态链接和 UTM 参数的长 URL
///
- (nullable instancetype)initWithLongLink:(NSURL * _Nonnull)longLink OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12DynamicLinks30DynamicLinkAnalyticsParameters")
@interface DynamicLinkAnalyticsParameters : NSObject
/// The UTM source (e.g., google, newsletter).
@property (nonatomic, copy) NSString * _Nullable source;
/// The UTM medium (e.g., cpc, email).
@property (nonatomic, copy) NSString * _Nullable medium;
/// The UTM campaign name.
@property (nonatomic, copy) NSString * _Nullable campaign;
/// The UTM term (e.g., paid keywords).
@property (nonatomic, copy) NSString * _Nullable term;
/// The UTM content (e.g., banner_ad).
@property (nonatomic, copy) NSString * _Nullable content;
- (nonnull instancetype)initWithSource:(NSString * _Nullable)source medium:(NSString * _Nullable)medium campaign:(NSString * _Nullable)campaign term:(NSString * _Nullable)term content:(NSString * _Nullable)content OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12DynamicLinks28DynamicLinkAndroidParameters")
@interface DynamicLinkAndroidParameters : NSObject
/// The Android app’s package name.
@property (nonatomic, readonly, copy) NSString * _Nonnull packageName;
/// The link to open when the app isn’t installed.
@property (nonatomic, copy) NSURL * _Nullable fallbackURL;
/// The version code of the minimum version of the app that can open the link.
@property (nonatomic) NSInteger minimumVersion;
/// Initializes the Android parameters with a required package name.
- (nonnull instancetype)initWithPackageName:(NSString * _Nonnull)packageName fallbackURL:(NSURL * _Nullable)fallbackURL minimumVersion:(NSInteger)minimumVersion OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12DynamicLinks21DynamicLinkComponents")
@interface DynamicLinkComponents : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12DynamicLinks24DynamicLinkIOSParameters")
@interface DynamicLinkIOSParameters : NSObject
/// The App Store ID of the iOS app in App Store.
@property (nonatomic, copy) NSString * _Nullable appStoreID;
/// The link to open when the app isn’t installed.
@property (nonatomic, copy) NSURL * _Nullable fallbackURL;
/// The link to open on iPads when the app isn’t installed.
@property (nonatomic, copy) NSURL * _Nullable iPadFallbackURL;
/// The minimum version of your app that can open the link.
@property (nonatomic, copy) NSString * _Nullable minimumAppVersion;
- (nonnull instancetype)initWithAppStoreID:(NSString * _Nullable)appStoreID fallbackURL:(NSURL * _Nullable)fallbackURL iPadFallbackURL:(NSURL * _Nullable)iPadFallbackURL minimumAppVersion:(NSString * _Nullable)minimumAppVersion OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12DynamicLinks43DynamicLinkItunesConnectAnalyticsParameters")
@interface DynamicLinkItunesConnectAnalyticsParameters : NSObject
/// The iTunes Connect affiliate token.
@property (nonatomic, copy) NSString * _Nullable affiliateToken;
/// The iTunes Connect campaign token.
@property (nonatomic, copy) NSString * _Nullable campaignToken;
/// The iTunes Connect provider token.
@property (nonatomic, copy) NSString * _Nullable providerToken;
- (nonnull instancetype)initWithAffiliateToken:(NSString * _Nullable)affiliateToken campaignToken:(NSString * _Nullable)campaignToken providerToken:(NSString * _Nullable)providerToken OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class Warning;
/// 缩短链接的响应
SWIFT_CLASS("_TtC12DynamicLinks26DynamicLinkShortenResponse")
@interface DynamicLinkShortenResponse : NSObject
/// 链接 ID
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
/// 短链接字符串
@property (nonatomic, readonly, copy) NSString * _Nonnull shortLinkString;
/// 原始链接
@property (nonatomic, readonly, copy) NSString * _Nonnull link;
/// 链接名称
@property (nonatomic, readonly, copy) NSString * _Nullable name;
/// 警告信息列表
@property (nonatomic, readonly, copy) NSArray<Warning *> * _Nonnull warnings;
/// 短链接 URL
@property (nonatomic, readonly, copy) NSURL * _Nullable shortLink;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12DynamicLinks15DynamicLinksSDK")
@interface DynamicLinksSDK
/// SDK 版本号
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DynamicLinksSDK * _Nonnull shared;)
+ (DynamicLinksSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// 设置是否信任所有证书（仅开发环境使用）
/// 必须在 initialize() 之前调用
+ (SWIFT_METATYPE(DynamicLinksSDK) _Nonnull)setTrustAllCerts:(BOOL)enabled;
/// Whether analytics data collection is enabled (deferred deeplink & install confirmation).
/// When disabled, regular deep link handling (Universal Links) continues to work normally.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL analyticsEnabled;)
+ (BOOL)analyticsEnabled SWIFT_WARN_UNUSED_RESULT;
+ (void)setAnalyticsEnabled:(BOOL)newValue;
/// Enable or disable analytics data collection.
/// When disabled, <code>checkDeferredDeeplink</code> returns not-found and <code>confirmInstall</code> is a no-op.
/// Regular deep link handling (Universal Links) is not affected.
+ (SWIFT_METATYPE(DynamicLinksSDK) _Nonnull)setAnalyticsEnabled:(BOOL)enabled;
/// 初始化 SDK（简单版本，不自动检查 Deferred Deeplink）
/// \param baseUrl 后端 API Base URL (例如 “https://api.grivn.com”)
///
/// \param secretKey Secret Key（通过 X-API-Key header 发送）
///
/// \param projectId 项目 ID（可选，用于创建链接时指定所属项目）
///
+ (DynamicLinksSDK * _Nonnull)initializeWithBaseUrl:(NSString * _Nonnull)baseUrl secretKey:(NSString * _Nonnull)secretKey projectId:(NSString * _Nullable)projectId;
/// 检查是否已初始化
+ (BOOL)isInitialized SWIFT_WARN_UNUSED_RESULT;
/// 设置项目 ID（可在 initialize() 后单独设置）
/// \param projectId 项目 ID（用于创建链接）
///
- (DynamicLinksSDK * _Nonnull)setProjectId:(NSString * _Nonnull)projectId;
/// 配置允许的域名列表
/// \param allowedHosts 允许的域名列表 (例如 [“acme.wayp.link”, “preview.acme.wayp.link”])
///
+ (void)configureWithAllowedHosts:(NSArray<NSString *> * _Nonnull)allowedHosts;
@end

@interface DynamicLinksSDK (SWIFT_EXTENSION(DynamicLinks))
/// Check if pasteboard may contain a dynamic link (does NOT trigger iOS 16+ paste prompt)
/// Use this to decide whether to show a “Paste link” button/banner.
/// Only when user taps the button should you call <code>handlePasteboardDynamicLink()</code>.
- (BOOL)hasPossibleDynamicLink SWIFT_WARN_UNUSED_RESULT;
/// 重置粘贴板检查状态（用于测试）
- (void)resetPasteboardCheck;
@end

@interface DynamicLinksSDK (SWIFT_EXTENSION(DynamicLinks))
/// 重置首次启动状态（用于测试）
- (void)resetDeferredDeeplinkState;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
